# Generated by Django 3.1.7 on 2021-03-30 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20210326_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='author_user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author_issue', to='quickstart.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issues',
            name='project_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='api.projects'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='author_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_project', to=settings.AUTH_USER_MODEL),
        ),
    ]
