# Generated by Django 3.1.7 on 2021-03-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210330_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='priority',
            field=models.CharField(choices=[('FAIBLE', 'FAIBLE'), ('MOYENNE', 'MOYENNE'), ('ELEVEE', 'ELEVEE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='issues',
            name='statut',
            field=models.CharField(choices=[('A faire', 'A faire'), ('En cours', 'En Cours'), ('Terminé', 'Termine')], max_length=30),
        ),
        migrations.AlterField(
            model_name='issues',
            name='tag',
            field=models.CharField(choices=[('BUG', 'BUG'), ('AMELIORATION', 'AMELIORATION'), ('TACHE', 'TACHE')], max_length=30),
        ),
    ]
